# Generated by Django 5.2.1 on 2025-05-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='availabe',
        ),
    ]
