# Generated by Django 5.2.1 on 2025-06-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_booking_booked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
