# Generated by Django 5.2.1 on 2025-05-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='available',
        ),
    ]
