# Generated by Django 5.2.1 on 2025-05-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_room_owner_alter_room_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='owner',
        ),
    ]
